name: 'Dispatch merged PR notification'

# Ensures that only one workflow is run per branch at a time.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  push:
    branches:
      - master
      - release-[0-9]+.[0-9]+

permissions: {} # disables permissions for all of the available permissions

jobs:
  dispatch-merged-pr-notififcation:
    name: Dispatch merged PR notification
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.NOTIFY_BOT_PAT_TOKEN }}
        run: |
          gh api repos/${{ vars.NOTIFY_REPO_OWNER }}/${{ vars.NOTIFY_REPO_NAME }}/dispatches \
            -X POST \
            -f event_type=${{ vars.NOTIFY_EVENT_TYPE }} \
            -f 'client_payload[branch]=${{ github.ref_name }}'
